[package]
version = "0.1.0"
name = "modpow"
edition = "2021"

[dependencies]
sp1-zkvm = { workspace = true }
sp1-lib = { workspace = true }
crypto-bigint = "0.5.5"
bytemuck = { version = "1.16.1", features = ["derive"] }
num-bigint = { workspace = true }
num-traits = { workspace = true }
